# Generated by Django 3.1.7 on 2021-04-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='', upload_to='posts/')),
            ],
        ),
    ]
