# Generated by Django 3.1.7 on 2021-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210303_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
