# Generated by Django 3.1.7 on 2021-03-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210306_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ticket', models.CharField(max_length=500)),
            ],
        ),
    ]
