# Generated by Django 3.1.7 on 2021-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oder_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('cartjson', models.CharField(max_length=500)),
            ],
        ),
    ]
