# Generated by Django 3.1.7 on 2021-03-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_id',
            new_name='order_id',
        ),
    ]
