# Generated by Django 3.1.7 on 2021-03-16 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
