# Generated by Django 3.1.7 on 2021-03-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210316_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='update',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
